### PR TITLE
Include all loader errors when failing

### LINKED ISSUE #2736: Include missing exports, loader transcript when available
On Windows, when we enable loader snaps in `dynamic-linker` in the fuzzer help check, we get an extensive loader transcript. When a specific export is missing from the DLL that was resolved, we also get information about which export is missing.

1. When a DLL is found, but one or more expected exports are missing, report them. The wrong DLL was probably found and loaded.
2. On error on Windows, include the entire loader transcript in the task error logs.

[AB#36071](https://fuzzfest.visualstudio.com/5eaacf23-2084-4d62-8fbe-7d37326a8b74/_workitems/edit/36071)

### PR DESCRIPTION
**Pull request by Porges**
Closes #2736.

Include all errors from the loader transcript when looking for missing DLLs. This will help users to analyze the problem, as this information can include missing symbols, etc.

### CODE REVIEW

File: src/agent/onefuzz/src/libfuzzer.rs [hunk 1]
```diff
@@ -306,25 +306,26 @@ impl LibFuzzer {
...
             // To provide user-actionable errors, try to identify any missing shared libraries.
             match self.find_missing_libraries().await {
-                Ok(missing) => {
+                Ok((missing, errors)) => {
                     if missing.is_empty() {
-                        bail!("fuzzer does not respond to '-help=1'. no missing shared libraries detected. output: {:?}", result);
+                        bail!("fuzzer does not respond to '-help=1'. no missing shared libraries detected. output: {result:?}");
                     } else {
                         let missing = missing.join(", ");
+                        let all_errors = errors.join("\n");
```
Comment (tevoinea) [inline src/agent/onefuzz/src/libfuzzer.rs:314]: We should put the correct line ending depending on the platform

**Review by tevoinea — APPROVED** [review]

File: src/agent/onefuzz/src/libfuzzer.rs (hunk 1 above)
Comment (Porges) [reply src/agent/onefuzz/src/libfuzzer.rs:314]: I just checked and `println` in Rust _always_ uses `\n` and never `\r\n`, so I’ll leave this as-is.
