### PR TITLE
Use sync pointers for updating `ModuleCache` off-thread

### LINKED ISSUE #1031: Coverage task does not maintain internal invariant on error
OneFuzz: 2.23.1
OS: Windows

In the coverage task, the (blocking, non-async) recording itself occurs on a new OS thread, via `spawn_blocking()`.

To avoid needing to use `sync` primitives, we just `Option::take()` the `TaskContext`'s `ModuleCache`, and pass it to the worker thread, restoring it on completion. However, if recording fails, we now retry some number of times, as of #978. But recording can fail while the worker thread owns the `ModuleCache`, which it will drop on its return with `Err`. We will then early-exit `TaskContext::record_impl()`, without restoring the `Option<ModuleCache>`, which can result in a panic.

Switch to using threadsafe smart pointers, instead.

### PR DESCRIPTION
**Pull request by ranweiler**
Closes #1031.

### CODE REVIEW

File: src/agent/onefuzz-agent/src/tasks/coverage/generic.rs [hunk 1]
```diff
@@ -322,40 +321,35 @@ impl<'a> TaskContext<'a> {
     }
 }
 
-struct Recorded {
```
Comment (ranweiler) [inline src/agent/onefuzz-agent/src/tasks/coverage/generic.rs:325]: We're no longer passing around `ModuleCache` ownership, so this type is redundant.

**Review by bmc-msft — APPROVED** [review]
