### PR TITLE
Require explicit call to async `Expand::machine_id()`

### LINKED ISSUE #1351: Expanding machine_id crashes OneFuzz agent
## Information

- Onefuzz version: 3.1.0
- OS: Linux

## Provide detailed reproduction steps (if any)

1. Include `{machine_id}` in `target_options`

### Expected result

`{machine_id}` to be expanded to the machine identifier

### Actual result

The OneFuzz agent crashes. Error from job `dcd6740a-6ee7-4b78-bc9c-88179af2dadf`:

```
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:208:50
   9:     0x555555d7810c - std::panicking::default_hook::h5a8e74a76ce290a7
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:225:9
  10:     0x555555d7810c - std::panicking::rust_panic_with_hook::h67c812a4fe9d4c91
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:622:17
  11:     0x555555dc5404 - std::panicking::begin_panic::{{closure}}::hb4d407006735f60c
  12:     0x555555dc51cc - std::sys_common::backtrace::__rust_end_short_backtrace::h997cb0531526c585
  13:     0x55555564133a - std::panicking::begin_panic::hf01f70e16f474514
  14:     0x55555588a842 - tokio::runtime::thread_pool::ThreadPool::block_on::h742a0721f59325ba
  15:     0x55555589f606 - tokio::runtime::Runtime::block_on::h0f7360209fc181ab
  16:     0x555555871dfb - onefuzz::expand::Expand::machine_id::hee302ad91680b05d
  17:     0x55555586f579 - core::ops::function::Fn::call::h1cd9ef38b06186ec
  18:     0x555555874b25 - onefuzz::expand::Expand::replace_value::h81b1fe273a24782d
  19:     0x555555a319c3 - onefuzz::expand::Expand::evaluate_value::h68429f1fe6c4084b
  20:     0x555555a31d7a - onefuzz::expand::Expand::evaluate::h5e69d52a4141622a
  21:     0x555555ab56fe - onefuzz_agent::tasks::fuzz::supervisor::spawn::{{closure}}::hfff9be925ed25b9a
  22:     0x555555a98df0 - onefuzz_agent::managed::cmd::run::{{closure}}::hf7ce9d76f067bc40
  23:     0x555555a586b9 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h62d01efe52955955
  24:     0x5555559fd2f2 - tokio::park::thread::CachedParkThread::block_on::he9a715ff60608466
  25:     0x555555a2b8ef - tokio::runtime::thread_pool::ThreadPool::block_on::hd14e8c303a32fcbb
  26:     0x555555954fcf - tokio::runtime::Runtime::block_on::h95a7b26ee9442d84
  27:     0x55555590284c - onefuzz_agent::main::h5766a9fb23cd3d70
  28:     0x555555977393 - std::sys_common::backtrace::__rust_begin_short_backtrace::hbf390f5f40f65fcb
  29:     0x55555590e9ad - std::rt::lang_start::{{closure}}::hb8bef157736927cb
  30:     0x555555d788af - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::ha9408abe89f69dc4
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/ops/function.rs:259:13
  31:     0x555555d788af - std::panicking::try::do_call::h5b0cc9e9102acb65
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:401:40
  32:     0x555555d788af - std::panicking::try::hddc7f8229138b3ba
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:365:19
  33:     0x555555d788af - std::panic::catch_unwind::hfa401ff8bab2986e
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panic.rs:434:14
  34:     0x555555d788af - std::rt::lang_start_internal::{{closure}}::h8163422320d11405
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/rt.rs:45:48
  35:     0x555555d788af - std::panicking::try::do_call::hc742cc7bb4f0fb20
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:401:40
  36:     0x555555d788af - std::panicking::try::ha37d8d2dd1acf7d3
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:365:19
  37:     0x555555d788af - std::panic::catch_unwind::h8a5381d5ecf437bc
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panic.rs:434:14
  38:     0x555555d788af - std::rt::lang_start_internal::h7e2cee8c90d4a4d3
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/rt.rs:45:20
  39:     0x555555902ac2 - main
  40:     0x7ffff69fcbf7 - __libc_start_main
  41:     0x55555564449a - _start
```

### PR DESCRIPTION
**Pull request by hayleycall**
## Summary of the Pull Request
This PR address an issue with a panic occurring due to nested Tokio runtimes when expanding `{machine_id}` to machine identifier. This issue is documented in #1351. The fix was to update the `Expand` API by modifying the function `machine_id` that got and set the machine identifier by making it async so that it would not need to use another Tokio runtime. Now this function runs at the time `Expand` is constructed rather than at the time of expanding the particular `{machine_id}` value when expanding each value in `target_options`.

## PR Checklist
* [X] Applies to work item: #1351
* [X] CLA signed. If not, go over [here](https://cla.opensource.microsoft.com/microsoft/onefuzz) and sign the CLI.
* [X] Tests added/passed
* [ ] Requires documentation to be updated
* [ ] I've discussed this with core contributors already. If not checked, I'm ready to accept this work might be rejected in favor of a different grand plan. Issue number where discussion took place: #xxx

## Info on Pull Request

Modified `machine_id` function, called this function at appropriate constructions of `Expand`. Closes #1351 

## Validation Steps Performed

Modified `test_expand_machine_id` to be async to properly test that modified function expands `{machine_id}` without panic.

### CODE REVIEW

File: src/agent/onefuzz/src/expand.rs [hunk 1]
```diff
@@ -518,12 +509,11 @@ mod tests {
...
-    fn test_expand_machine_id() -> Result<()> {
-        // verify {machine_id} expands to a UUID, but don't worry about the
-        // actual value of the UUID
-        let result = Expand::new().evaluate_value("{machine_id}")?;
-        Uuid::parse_str(&result)?;
+    #[tokio::test]
+    async fn test_expand_machine_id() -> Result<()> {
+        let expand = Expand::new().machine_id().await?;
+        let expanded = expand.evaluate_value("{machine_id}")?;
+        Uuid::parse_str(&expanded)?;
```
Comment (ranweiler) [inline src/agent/onefuzz/src/expand.rs:516]: Let's preserve the comment, for future readers!

```suggestion
        // Check that "{machine_id}" expands to a valid UUID, but don't worry about the actual value.
        Uuid::parse_str(&expanded)?;
```

File: src/agent/onefuzz/src/expand.rs [hunk 2]
```diff
@@ -110,23 +110,14 @@ impl<'a> Expand<'a> {
...
-    // Note: this spawns it's own tokio runtime as it's not really workable to
-    // refactor the get_machine_id into a blockable version, however... as this
-    // is implemented as a ExpandedValue::Mapping, launching a tokio runtime
-    // occurs when users actively attempt to expand {machine_id}.
-    fn machine_id(&self, _format_str: &str) -> Result<Option<ExpandedValue<'a>>> {
-        let rt = tokio::runtime::Runtime::new()?;
-        let machine_id = rt.block_on(get_machine_id())?;
-        let value = machine_id.to_hyphenated().to_string();
-        Ok(Some(ExpandedValue::Scalar(value)))
+    pub async fn machine_id(self) -> Result<Expand<'a>> {
```
Comment (ranweiler) [inline src/agent/onefuzz/src/expand.rs:117]: Let's add a comment to remind ourselves why this exists.
```suggestion
    // Must be manually called to enable the use of async library code.
    pub async fn machine_id(self) -> Result<Expand<'a>> {
```

**Review by ranweiler — COMMENTED** [review]
Looking good! Added a few documentation suggestions.

Also, two remaining questions:
- Are there uses of `Expand` elsewhere that also need to be updated, such as in the `onefuzz` library crate?
- Have we manually tested this with a job that tries to expand `{machine_id}`?

File: src/agent/onefuzz/src/expand.rs [hunk 3]
```diff
@@ -110,23 +110,15 @@ impl<'a> Expand<'a> {
...
-    // refactor the get_machine_id into a blockable version, however... as this
-    // is implemented as a ExpandedValue::Mapping, launching a tokio runtime
-    // occurs when users actively attempt to expand {machine_id}.
-    fn machine_id(&self, _format_str: &str) -> Result<Option<ExpandedValue<'a>>> {
-        let rt = tokio::runtime::Runtime::new()?;
-        let machine_id = rt.block_on(get_machine_id())?;
-        let value = machine_id.to_hyphenated().to_string();
-        Ok(Some(ExpandedValue::Scalar(value)))
+    // Must be manually called to enable the use of async library code.
+    pub async fn machine_id(self) -> Result<Expand<'a>> {
```
Comment (bmc-msft) [inline src/agent/onefuzz/src/expand.rs:118]: Perhaps this could be done as part of `Expand::new()`, which would be useful for enabling future environment specific options, rather than requiring the callers to have to call .machine_id().await?

Comment (ranweiler) [reply src/agent/onefuzz/src/expand.rs:118]: That was my initial thought, but I avoided suggesting that because I didn't want to force `new()` to itself be async, which would complicate some non-`async` uses of `Expand`. But revisiting the idea, we could just add an _additional_ ctor that _is_ async, and assumes it is being run in a managed task VM context. We could also just impl `Default` to provide the non-`async` ctor.

Let's address that in a follow-up PR.

**Review by chkeita — APPROVED** [review]
