### PR TITLE
Set TSan options based on external symbolizer

### LINKED ISSUE #1770: Add first-tier support for ThreadSanitizer
We nominally support [TSan](https://releases.llvm.org/11.0.0/tools/clang/docs/ThreadSanitizer.html) instrumentation, and even test basic [stacktrace parsing](https://github.com/microsoft/onefuzz/blob/5aceb258435954343306909cefd82eb0a71f29b5/src/agent/stacktrace-parser/data/stack-traces/tsan-linux-llvm10-data-race.txt).

However:
- Our support for TSan logs is probably missing many cases
- We support, but don't help configuration of a known-good external symbolizer (e.g. `TSAN_OPTIONS=external_symbolizer_path=/onefuzz/bin/llvm-symbolizer`)
- We don't test any [flags](https://github.com/google/sanitizers/wiki/ThreadSanitizerFlags)

Add this, for platforms with TSan support.

### PR DESCRIPTION
**Pull request by ranweiler**
- Add `LlvmSymbolizer` wrapper around validated paths to external `llvm-symbolizer` exes
- Pivot sanitizer environment variable generation on `LlvmSymbolizer`
- Set external symbolizer path in `TSAN_OPTIONS`

Closes #1770.

### CODE REVIEW

**Review by stishkin — APPROVED** [review]

**Review by chkeita — APPROVED** [review]

File: src/agent/onefuzz/src/sanitizer.rs [hunk 1]
```diff
@@ -2,18 +2,138 @@
...
+    pub fn as_str(&self) -> &str {
+        &self.path
+    }
+
+    pub fn sanitizer_env_vars(&self) -> HashMap<String, String> {
+        let mut env = HashMap::default();
+
+        env.insert("ASAN_SYMBOLIZER_PATH".to_owned(), self.path.clone());
+
+        let options = format!("external_symbolizer={}", self.path);
```
Comment (ranweiler) [inline src/agent/onefuzz/src/sanitizer.rs:50]: Wrong, should be `external_symbolizer_path` ([docs](https://github.com/google/sanitizers/wiki/ThreadSanitizerFlags)).

File: src/agent/onefuzz/src/sanitizer.rs [hunk 2]
```diff
@@ -2,18 +2,138 @@
...
+
+    #[test]
+    fn test_sanitizer_env_vars() -> Result<()> {
+        const SYMBOLIZER_PATH: &str = "/my/llvm-symbolizer";
+        let symbolizer = LlvmSymbolizer::new(SYMBOLIZER_PATH)?;
+        let vars = symbolizer.sanitizer_env_vars();
+
+        assert_eq!(vars["ASAN_SYMBOLIZER_PATH"], SYMBOLIZER_PATH);
+
+        let tsan_options = format!("external_symbolizer={}", SYMBOLIZER_PATH);
```
Comment (ranweiler) [inline src/agent/onefuzz/src/sanitizer.rs:132]: Should be `external_symbolizer_path` ([docs](https://github.com/google/sanitizers/wiki/ThreadSanitizerFlags)).

**Review by hayleycall — APPROVED** [review]
