### PR TITLE
Make modules case insenstive on windows

### LINKED ISSUE #3525: Code coverage allow list and modules should be case insensitive on Windows
## Information

- Onefuzz version: 8.8
- OS: Windows

## Provide detailed reproduction steps (if any)

Paths on Windows are not case sensitive, thus we should not be case sensitive when when evaluating coverage allow list for source or modules.

On Linux, the behavior should not change.

[AB#166580](https://fuzzfest.visualstudio.com/5eaacf23-2084-4d62-8fbe-7d37326a8b74/_workitems/edit/166580)

### PR DESCRIPTION
**Pull request by tevoinea**
## Summary of the Pull Request

_What is this about?_

Closes #3525

## Info on Pull Request

_What does this include?_

* Binary and source coverage allowlists are now case insensitive on Windows
* Modules that are loaded on Windows are tracked internally in a case insensitive way
* Tests

## Validation Steps Performed

_How does someone test & validate?_

* Added a test that a source allowlist of `inlinee.exe` will pick up a binary compiled as `Inlinee.exe`
* Added a test that the modules loaded from `Inlinee.exe` are all only lowercase

### CODE REVIEW

File: src/agent/coverage/tests/snapshot.rs [hunk 1]
```diff
@@ -52,6 +53,13 @@ fn windows_snapshot_tests() {
             .record()
             .unwrap();
 
+        // Windows modules should be case insensitive
```
Comment (ranweiler) [inline src/agent/coverage/tests/snapshot.rs:56]: IIUC: this test is just asserting that the names OneFuzz uses to track modules / report coverage are _normalized_ to be all-lowercase.

That's good, but maybe update the comment, because you really need something else to be true to test that the comparisons _based on this normalization_ are also effectively case-insensitive.

File: src/agent/debugger/src/module.rs [hunk 2]
```diff
@@ -47,6 +47,8 @@ impl Module {
             "???".into()
         });
 
+        let path = PathBuf::from(path.as_os_str().to_ascii_lowercase());
```
Comment (ranweiler) [inline src/agent/debugger/src/module.rs:50]: Note that this change impacts Linux, too.

File: src/agent/coverage/src/allowlist.rs [hunk 3]
```diff
@@ -144,7 +144,13 @@ fn glob_to_regex(expr: &str) -> Result<Regex> {
     // Anchor to line start and end.
     let expr = format!("^{expr}$");
 
-    Ok(Regex::new(&expr)?)
+    let mut rb = RegexBuilder::new(&expr);
+
+    if cfg!(windows) {
+        rb.case_insensitive(true);
```
Comment (ranweiler) [inline src/agent/coverage/src/allowlist.rs:150]: The allowlist matching is unit-tested. I suggest adding at least one test decorated with `[cfg(target_os = "windows")]` which exercises the new matching logic. Maybe also a Linux-only test that demonstrates case-sensitivity on that platform.

File: src/agent/coverage/tests/snapshot.rs (hunk 1 above)
Comment (ranweiler) [reply src/agent/coverage/tests/snapshot.rs:56]: I think your file renaming is meant to accomplish this semi-indirectly, but it would be good to document that somewhere if possible.

**Review by ranweiler — CHANGES_REQUESTED** [review]

File: src/agent/debugger/src/module.rs (hunk 2 above)
Comment (tevoinea) [reply src/agent/debugger/src/module.rs:50]: I thought it wouldn't since this function takes a `HANDLE` which comes from the `windows` crate.

Comment (ranweiler) [reply src/agent/debugger/src/module.rs:50]: Wow, my coffee hasn't fully hit yet. You're absolutely right, I totally misread the file path. 🥴

So, a question, instead: this `debugger` crate is also used by the Windows `input-tester` crate. Does normalizing here change the behavior on that end? For this PR, maybe it would be safer to do the normalization explicitly in the `coverage` code for now, where the `debugger` crate's `Module` gets used.

File: src/agent/coverage/src/allowlist.rs (hunk 3 above)
Comment (tevoinea) [reply src/agent/coverage/src/allowlist.rs:150]: That unit test caught a bug! Setting the case_inensitive flag in the RegexBuilder didn't get passed along when we convert from Regex to RegexSet in a different part of the code.

File: src/agent/debugger/src/module.rs (hunk 2 above)
Comment (tevoinea) [reply src/agent/debugger/src/module.rs]: I updated the code to only become case-insensitive when we convert from binary to source coverage. That way we get what we're ultimately looking for (a cleaner/more organized cobertura file) with no risk to changing the behavior for the rest of the program.

File: src/agent/coverage/tests/snapshot.rs (hunk 1 above)
Comment (tevoinea) [reply src/agent/coverage/tests/snapshot.rs]: Updated the comment to call out the importance of the name of the test file

File: src/agent/coverage/src/source.rs [hunk 4]
```diff
@@ -104,13 +104,18 @@ pub fn binary_to_source_coverage(
                         };
 
                         if let Some(file) = location.file() {
+                            let file_path = if cfg!(windows) {
+                                // Windows paths are case insensitive.
+                                FilePath::new(file.full_path().to_ascii_lowercase())?
+                            } else {
+                                FilePath::new(file.full_path())?
+                            };
```
Comment (Porges) [inline src/agent/coverage/src/source.rs:112]: We should do this once up-front rather than every time we examine a location

Comment (tevoinea) [reply src/agent/coverage/src/source.rs]: I used the `Transformer` available in the symbolic-symcache crate so we only do the modification once.
