### PR TITLE
Fix logic of marking task as failed

### LINKED ISSUE #3084: Fix logic of marking task as failed
When marking a task as failed when the node is shutting down, we should check the state of the task and make sure it is not already shutting down.

[AB#148812](https://fuzzfest.visualstudio.com/5eaacf23-2084-4d62-8fbe-7d37326a8b74/_workitems/edit/148812)

### PR DESCRIPTION
**Pull request by chkeita**
- Do not mark task as failed if it is already in the shutting down state
- accumulate errors when setting task error to understand the context
- refactor the Error record

closes #3084

### CODE REVIEW

File: src/ApiService/ApiService/onefuzzlib/NodeOperations.cs [hunk 1]
```diff
@@ -585,14 +585,19 @@ sealed record NodeInfo(Node Node, Scaleset Scaleset, string InstanceId);
...
-    public async Async.Task MarkTasksStoppedEarly(Node node, Error? error = null) {
-        if (error is null) {
-            error = new Error(ErrorCode.TASK_FAILED, new[] { $"node reimaged during task execution.  machine_id: {node.MachineId}" });
-        }
-
+    public async Async.Task MarkTasksStoppedEarly(Node node, Error? error) {
         await foreach (var entry in _context.NodeTasksOperations.GetByMachineId(node.MachineId)) {
             var task = await _context.TaskOperations.GetByTaskId(entry.TaskId);
-            if (task is not null) {
+            if (task is not null && !TaskStateHelper.ShuttingDown(task.State)) {
```
Comment (chkeita) [inline src/ApiService/ApiService/onefuzzlib/NodeOperations.cs:591]: This is the fix

File: src/ApiService/ApiService/onefuzzlib/ImageReference.cs [hunk 2]
```diff
@@ -46,18 +46,17 @@ public abstract record ImageReference {
...
+                return Error.Create(
                     ErrorCode.INVALID_IMAGE,
-                    new[] { $"Unknown image resource type: {identifier.ResourceType}" });
+                    $"Unknown image resource type: {identifier.ResourceType}");
             }
         } catch (FormatException) {
             // not an ARM identifier, try to parse a marketplace image:
             var imageParts = image.Split(":");
-            // The python code would throw if more than 4 parts are found in the split
+            // The python code would throw if more than 4 parts are foud in the split
```
Comment (Porges) [inline src/ApiService/ApiService/onefuzzlib/ImageReference.cs:56]: accidental deletion
```suggestion
            // The python code would throw if more than 4 parts are found in the split
```

**Review by Porges — APPROVED** [review]

File: src/ApiService/ApiService/onefuzzlib/ProxyOperations.cs [hunk 3]
```diff
@@ -213,7 +213,7 @@ public ProxyOperations(ILogTracer log, IOnefuzzContext context)
 
     private async System.Threading.Tasks.Task<Proxy> SetProvisionFailed(Proxy proxy, VirtualMachineInstanceView? instanceView) {
         var errors = GetErrors(proxy, instanceView).ToArray();
```
Comment (tevoinea) [inline src/ApiService/ApiService/onefuzzlib/ProxyOperations.cs:215]: NIT: Don't need `ToArray` if you're going to `ToList` after
```suggestion
        var errors = GetErrors(proxy, instanceView);
```

**Review by tevoinea — APPROVED** [review]
