### PR TITLE
Make WebhookMessageEventGrid compatible with the event grid format

### LINKED ISSUE #3285: WebhookMessageEventGrid is not compatible with the eventgrid  message schema
WebhookMessageEventGrid is not compatible with the eventgrid  message schema which is causing this exception when an event grid message is sent. 

```json 
{
    "error": {
        "code": "BadRequest",
        "message": "This resource is configured for 'EventGridEvent' schema. Received unexpected property 'sas_url' in JSON which does not conform to the expected schema. Report '1525163c-f23c-4abb-a751-0f24444a3c97:1:7/10/2023 6:01:16 PM (UTC)' to our forums for assistance or raise a support ticket.",
        "details": [{
            "code": "InputJsonInvalid",
            "message": "This resource is configured for 'EventGridEvent' schema. Received unexpected property 'sas_url' in JSON which does not conform to the expected schema. Report '1525163c-f23c-4abb-a751-0f24444a3c97:1:7/10/2023 6:01:16 PM (UTC)' to our forums for assistance or raise a support ticket."
    }]
  }
}
```

The record should be updated to be compatible with the [schema](https://learn.microsoft.com/en-us/azure/event-grid/event-schema#event-schema)

[AB#160661](https://fuzzfest.visualstudio.com/5eaacf23-2084-4d62-8fbe-7d37326a8b74/_workitems/edit/160661)

### PR DESCRIPTION
**Pull request by chkeita**
## Summary of the Pull Request

Updated `WebhookMessageEventGrid` 
Updated the dataVersion field to 2.0

closes #3285

### CODE REVIEW

File: src/ApiService/ApiService/OneFuzzTypes/Webhooks.cs [hunk 1]
```diff
@@ -25,17 +25,23 @@ public record WebhookMessage(Guid EventId,
...
     [property: JsonPropertyName("dataVersion")] string DataVersion,
     string Subject,
     [property: JsonPropertyName("EventType")] EventType EventType,
     [property: JsonPropertyName("eventTime")] DateTimeOffset EventTime,
     Guid Id,
-    [property: TypeDiscrimnatorAttribute("EventType", typeof(EventTypeProvider))]
-    [property: JsonConverter(typeof(BaseEventConverter))]
-    BaseEvent Data,
-    Uri SasUrl,
-    String Version = "1.0");
```
Comment (Porges) [inline src/ApiService/ApiService/OneFuzzTypes/Webhooks.cs:38]: Should we keep the Version number and increment it?

**Review by stishkin — APPROVED** [review]
Assuming that you tested this
